package workflows

import (
	"time"

	"github.com/google/uuid"
	tileboxv1 "github.com/tilebox/tilebox-go/protogen/tilebox/v1"
	workflowsv1 "github.com/tilebox/tilebox-go/protogen/workflows/v1"
	"github.com/tilebox/tilebox-go/query"
)

// StorageSubscriptionType identifies the notification delivery provider.
type StorageSubscriptionType string

const (
	StorageSubscriptionTypeUnspecified    StorageSubscriptionType = "unspecified"
	StorageSubscriptionTypeAWSSNS         StorageSubscriptionType = "aws_sns"
	StorageSubscriptionTypeGooglePubSub   StorageSubscriptionType = "google_pubsub"
	StorageSubscriptionTypeAzureEventGrid StorageSubscriptionType = "azure_event_grid"
)

// StorageSubscriptionConfig configures notification delivery.
// Set Type and the corresponding provider field. Azure Event Grid needs only Type;
// its delivery header and secret are generated by the server.
type StorageSubscriptionConfig struct {
	Type         StorageSubscriptionType
	AWSSNS       *AWSSNSStorageSubscription
	GooglePubSub *GooglePubSubStorageSubscription
}

// StorageSubscription receives object notifications for a storage location.
// To change delivery configuration, create a replacement and delete the old subscription.
type StorageSubscription struct {
	ID                uuid.UUID
	StorageLocationID uuid.UUID
	Type              StorageSubscriptionType
	// Endpoint is the HTTPS delivery URL to configure in the provider.
	Endpoint       string
	CreatedAt      time.Time
	AWSSNS         *AWSSNSStorageSubscription
	GooglePubSub   *GooglePubSubStorageSubscription
	AzureEventGrid *AzureEventGridStorageSubscription
}

// AWSSNSStorageSubscription identifies the SNS topic and its payload format.
type AWSSNSStorageSubscription struct {
	TopicARN string
	// MessageFormat is s3 (the default), earthsearch_stac, or usgs_landsat_c2.
	MessageFormat string
}

// GooglePubSubStorageSubscription identifies an authenticated, wrapped JSON push subscription.
type GooglePubSubStorageSubscription struct {
	// Subscription is the full projects/{project}/subscriptions/{subscription} resource name.
	Subscription string
	// ServiceAccountEmail is the expected authenticated identity; no service account key is accepted.
	ServiceAccountEmail string
	// Audience is returned by the server and must be configured as the push OIDC audience.
	Audience string
}

// AzureEventGridStorageSubscription contains server-generated delivery setup values.
// Use Event Grid schema with Microsoft.Storage.BlobCreated and the container subject prefix.
type AzureEventGridStorageSubscription struct {
	WebhookSecretHeader string
	// WebhookSecret is returned only on creation. Configure it as a secret delivery header.
	WebhookSecret string
}

// StorageEventType identifies an object event.
type StorageEventType string

const (
	StorageEventTypeUnspecified StorageEventType = "unspecified"
	StorageEventTypeCreated     StorageEventType = "created"
)

// StorageSubscriptionEvent is a received object notification and the jobs it triggered.
type StorageSubscriptionEvent struct {
	ID                    uuid.UUID
	StorageSubscriptionID uuid.UUID
	ObjectKey             string
	Type                  StorageEventType
	// EventTime is the provider event time, or nil when unavailable.
	EventTime     *time.Time
	ReceivedAt    time.Time
	TriggeredJobs []*TriggeredJob
}

// TriggeredJob identifies a job submitted by an automation for a matching object path.
type TriggeredJob struct {
	JobID        uuid.UUID
	AutomationID uuid.UUID
	GlobPattern  string
}

// StorageSubscriptionEventPage is one page of events in descending receipt order.
type StorageSubscriptionEventPage struct {
	Events     []*StorageSubscriptionEvent
	NextCursor *query.Cursor
}

func (c StorageSubscriptionConfig) toProto(storageLocationID uuid.UUID) *workflowsv1.CreateStorageSubscriptionRequest {
	request := workflowsv1.CreateStorageSubscriptionRequest_builder{
		StorageLocationId: tileboxv1.NewUUID(storageLocationID), Type: c.Type.toProto(),
	}
	if c.AWSSNS != nil {
		request.AwsSns = workflowsv1.AWSSNSStorageSubscription_builder{
			TopicArn: c.AWSSNS.TopicARN, MessageFormat: c.AWSSNS.MessageFormat,
		}.Build()
	}
	if c.GooglePubSub != nil {
		request.GooglePubsub = workflowsv1.GooglePubSubStorageSubscription_builder{
			Subscription: c.GooglePubSub.Subscription, ServiceAccountEmail: c.GooglePubSub.ServiceAccountEmail,
		}.Build()
	}
	if c.Type == StorageSubscriptionTypeAzureEventGrid {
		request.AzureEventGrid = &workflowsv1.AzureEventGridStorageSubscription{}
	}
	return request.Build()
}

func protoToStorageSubscription(subscription *workflowsv1.StorageSubscription) *StorageSubscription {
	if subscription == nil {
		return nil
	}
	result := &StorageSubscription{
		ID: protoIDToUUID(subscription.GetId()), StorageLocationID: protoIDToUUID(subscription.GetStorageLocationId()),
		Type: protoToStorageSubscriptionType(subscription.GetType()), Endpoint: subscription.GetEndpoint(),
	}
	if createdAt := subscription.GetCreatedAt(); createdAt != nil {
		result.CreatedAt = createdAt.AsTime()
	}
	if sns := subscription.GetAwsSns(); sns != nil {
		result.AWSSNS = &AWSSNSStorageSubscription{TopicARN: sns.GetTopicArn(), MessageFormat: sns.GetMessageFormat()}
	}
	if pubsub := subscription.GetGooglePubsub(); pubsub != nil {
		result.GooglePubSub = &GooglePubSubStorageSubscription{
			Subscription: pubsub.GetSubscription(), ServiceAccountEmail: pubsub.GetServiceAccountEmail(), Audience: pubsub.GetAudience(),
		}
	}
	if eventGrid := subscription.GetAzureEventGrid(); eventGrid != nil {
		result.AzureEventGrid = &AzureEventGridStorageSubscription{
			WebhookSecretHeader: eventGrid.GetWebhookSecretHeader(), WebhookSecret: eventGrid.GetWebhookSecret(),
		}
	}
	return result
}

func protoToStorageSubscriptionEvent(event *workflowsv1.StorageSubscriptionEvent) *StorageSubscriptionEvent {
	if event == nil {
		return nil
	}
	result := &StorageSubscriptionEvent{
		ID: protoIDToUUID(event.GetId()), StorageSubscriptionID: protoIDToUUID(event.GetStorageSubscriptionId()),
		ObjectKey: event.GetObjectKey(), Type: protoToStorageEventType(event.GetType()),
		TriggeredJobs: make([]*TriggeredJob, len(event.GetTriggeredJobs())),
	}
	if eventTime := event.GetEventTime(); eventTime != nil {
		timestamp := eventTime.AsTime()
		result.EventTime = &timestamp
	}
	if receivedAt := event.GetReceivedAt(); receivedAt != nil {
		result.ReceivedAt = receivedAt.AsTime()
	}
	for i, job := range event.GetTriggeredJobs() {
		result.TriggeredJobs[i] = &TriggeredJob{
			JobID: protoIDToUUID(job.GetJobId()), AutomationID: protoIDToUUID(job.GetAutomationId()), GlobPattern: job.GetGlobPattern(),
		}
	}
	return result
}

func protoToStorageSubscriptionType(subscriptionType workflowsv1.StorageSubscriptionType) StorageSubscriptionType {
	switch subscriptionType {
	case workflowsv1.StorageSubscriptionType_STORAGE_SUBSCRIPTION_TYPE_UNSPECIFIED:
		return StorageSubscriptionTypeUnspecified
	case workflowsv1.StorageSubscriptionType_STORAGE_SUBSCRIPTION_TYPE_AWS_SNS:
		return StorageSubscriptionTypeAWSSNS
	case workflowsv1.StorageSubscriptionType_STORAGE_SUBSCRIPTION_TYPE_GOOGLE_PUBSUB:
		return StorageSubscriptionTypeGooglePubSub
	case workflowsv1.StorageSubscriptionType_STORAGE_SUBSCRIPTION_TYPE_AZURE_EVENT_GRID:
		return StorageSubscriptionTypeAzureEventGrid
	default:
		return StorageSubscriptionTypeUnspecified
	}
}

func (t StorageSubscriptionType) toProto() workflowsv1.StorageSubscriptionType {
	switch t {
	case StorageSubscriptionTypeAWSSNS:
		return workflowsv1.StorageSubscriptionType_STORAGE_SUBSCRIPTION_TYPE_AWS_SNS
	case StorageSubscriptionTypeGooglePubSub:
		return workflowsv1.StorageSubscriptionType_STORAGE_SUBSCRIPTION_TYPE_GOOGLE_PUBSUB
	case StorageSubscriptionTypeAzureEventGrid:
		return workflowsv1.StorageSubscriptionType_STORAGE_SUBSCRIPTION_TYPE_AZURE_EVENT_GRID
	case StorageSubscriptionTypeUnspecified:
		return workflowsv1.StorageSubscriptionType_STORAGE_SUBSCRIPTION_TYPE_UNSPECIFIED
	default:
		return workflowsv1.StorageSubscriptionType_STORAGE_SUBSCRIPTION_TYPE_UNSPECIFIED
	}
}

func protoToStorageEventType(eventType workflowsv1.StorageEventType) StorageEventType {
	switch eventType {
	case workflowsv1.StorageEventType_STORAGE_EVENT_TYPE_UNSPECIFIED:
		return StorageEventTypeUnspecified
	case workflowsv1.StorageEventType_STORAGE_EVENT_TYPE_CREATED:
		return StorageEventTypeCreated
	default:
		return StorageEventTypeUnspecified
	}
}
