---
lint:
  # Run `protolint list` to see all available rules.
  rules:
    all_default: true

    # The specific linters to remove.
    remove:
      - REPEATED_FIELD_NAMES_PLURALIZED
      - FIELD_NAMES_EXCLUDE_PREPOSITIONS
      - MESSAGE_NAMES_EXCLUDE_PREPOSITIONS
      - RPCS_HAVE_COMMENT
      - FIELDS_HAVE_COMMENT
      - ENUM_FIELDS_HAVE_COMMENT
  rules_option:
    # MAX_LINE_LENGTH rule option.
    max_line_length:
      max_chars: 120
      tab_chars: 2
