// The internal lease service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: workflows/v1/lease.proto

package workflowsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId       *UUID                  `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseTimeout *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=lease_timeout,json=leaseTimeout,proto3" json:"lease_timeout,omitempty"`
}

func (x *Lease) Reset() {
	*x = Lease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflows_v1_lease_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_lease_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_workflows_v1_lease_proto_rawDescGZIP(), []int{0}
}

func (x *Lease) GetTaskId() *UUID {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *Lease) GetLeaseTimeout() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseTimeout
	}
	return nil
}

type TransferTaskLeaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskLeases []*Lease `protobuf:"bytes,1,rep,name=task_leases,json=taskLeases,proto3" json:"task_leases,omitempty"`
}

func (x *TransferTaskLeaseRequest) Reset() {
	*x = TransferTaskLeaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflows_v1_lease_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferTaskLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTaskLeaseRequest) ProtoMessage() {}

func (x *TransferTaskLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_lease_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTaskLeaseRequest.ProtoReflect.Descriptor instead.
func (*TransferTaskLeaseRequest) Descriptor() ([]byte, []int) {
	return file_workflows_v1_lease_proto_rawDescGZIP(), []int{1}
}

func (x *TransferTaskLeaseRequest) GetTaskLeases() []*Lease {
	if x != nil {
		return x.TaskLeases
	}
	return nil
}

type TransferTaskLeaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransferTaskLeaseResponse) Reset() {
	*x = TransferTaskLeaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflows_v1_lease_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferTaskLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTaskLeaseResponse) ProtoMessage() {}

func (x *TransferTaskLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_lease_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTaskLeaseResponse.ProtoReflect.Descriptor instead.
func (*TransferTaskLeaseResponse) Descriptor() ([]byte, []int) {
	return file_workflows_v1_lease_proto_rawDescGZIP(), []int{2}
}

type VacuumLeasesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VacuumLeasesRequest) Reset() {
	*x = VacuumLeasesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflows_v1_lease_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VacuumLeasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacuumLeasesRequest) ProtoMessage() {}

func (x *VacuumLeasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_lease_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacuumLeasesRequest.ProtoReflect.Descriptor instead.
func (*VacuumLeasesRequest) Descriptor() ([]byte, []int) {
	return file_workflows_v1_lease_proto_rawDescGZIP(), []int{3}
}

type VacuumLeasesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VacuumLeasesResponse) Reset() {
	*x = VacuumLeasesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflows_v1_lease_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VacuumLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacuumLeasesResponse) ProtoMessage() {}

func (x *VacuumLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_lease_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacuumLeasesResponse.ProtoReflect.Descriptor instead.
func (*VacuumLeasesResponse) Descriptor() ([]byte, []int) {
	return file_workflows_v1_lease_proto_rawDescGZIP(), []int{4}
}

var File_workflows_v1_lease_proto protoreflect.FileDescriptor

var file_workflows_v1_lease_proto_rawDesc = []byte{
	0x0a, 0x18, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x77, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x75, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x55, 0x49, 0x44,
	0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0d, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x50, 0x0a, 0x18, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52,
	0x0a, 0x74, 0x61, 0x73, 0x6b, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x65, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x56, 0x61, 0x63, 0x75,
	0x75, 0x6d, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x16, 0x0a, 0x14, 0x56, 0x61, 0x63, 0x75, 0x75, 0x6d, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcb, 0x01, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x73,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x64, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x26, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x61, 0x73,
	0x6b, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55,
	0x0a, 0x0c, 0x56, 0x61, 0x63, 0x75, 0x75, 0x6d, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x12, 0x21,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61,
	0x63, 0x75, 0x75, 0x6d, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x61, 0x63, 0x75, 0x75, 0x6d, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xbf, 0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x4c, 0x65, 0x61, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x77, 0x6f, 0x72,
	0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x57, 0x58, 0x58, 0xaa, 0x02,
	0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0c,
	0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x18, 0x57,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c,
	0x6f, 0x77, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workflows_v1_lease_proto_rawDescOnce sync.Once
	file_workflows_v1_lease_proto_rawDescData = file_workflows_v1_lease_proto_rawDesc
)

func file_workflows_v1_lease_proto_rawDescGZIP() []byte {
	file_workflows_v1_lease_proto_rawDescOnce.Do(func() {
		file_workflows_v1_lease_proto_rawDescData = protoimpl.X.CompressGZIP(file_workflows_v1_lease_proto_rawDescData)
	})
	return file_workflows_v1_lease_proto_rawDescData
}

var file_workflows_v1_lease_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_workflows_v1_lease_proto_goTypes = []interface{}{
	(*Lease)(nil),                     // 0: workflows.v1.Lease
	(*TransferTaskLeaseRequest)(nil),  // 1: workflows.v1.TransferTaskLeaseRequest
	(*TransferTaskLeaseResponse)(nil), // 2: workflows.v1.TransferTaskLeaseResponse
	(*VacuumLeasesRequest)(nil),       // 3: workflows.v1.VacuumLeasesRequest
	(*VacuumLeasesResponse)(nil),      // 4: workflows.v1.VacuumLeasesResponse
	(*UUID)(nil),                      // 5: workflows.v1.UUID
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_workflows_v1_lease_proto_depIdxs = []int32{
	5, // 0: workflows.v1.Lease.task_id:type_name -> workflows.v1.UUID
	6, // 1: workflows.v1.Lease.lease_timeout:type_name -> google.protobuf.Timestamp
	0, // 2: workflows.v1.TransferTaskLeaseRequest.task_leases:type_name -> workflows.v1.Lease
	1, // 3: workflows.v1.LeaseService.TransferTaskLease:input_type -> workflows.v1.TransferTaskLeaseRequest
	3, // 4: workflows.v1.LeaseService.VacuumLeases:input_type -> workflows.v1.VacuumLeasesRequest
	2, // 5: workflows.v1.LeaseService.TransferTaskLease:output_type -> workflows.v1.TransferTaskLeaseResponse
	4, // 6: workflows.v1.LeaseService.VacuumLeases:output_type -> workflows.v1.VacuumLeasesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_workflows_v1_lease_proto_init() }
func file_workflows_v1_lease_proto_init() {
	if File_workflows_v1_lease_proto != nil {
		return
	}
	file_workflows_v1_core_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_workflows_v1_lease_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflows_v1_lease_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferTaskLeaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflows_v1_lease_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferTaskLeaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflows_v1_lease_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VacuumLeasesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflows_v1_lease_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VacuumLeasesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workflows_v1_lease_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflows_v1_lease_proto_goTypes,
		DependencyIndexes: file_workflows_v1_lease_proto_depIdxs,
		MessageInfos:      file_workflows_v1_lease_proto_msgTypes,
	}.Build()
	File_workflows_v1_lease_proto = out.File
	file_workflows_v1_lease_proto_rawDesc = nil
	file_workflows_v1_lease_proto_goTypes = nil
	file_workflows_v1_lease_proto_depIdxs = nil
}
