// A sample tree workflow.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: examples/v1/workflow.proto

package examplesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SpawnWorkflowTreeTask is a task that spawns a tree of tasks.
type SpawnWorkflowTreeTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentLevel  int64                  `protobuf:"varint,1,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	Depth         int64                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	BranchFactor  int64                  `protobuf:"varint,3,opt,name=branch_factor,json=branchFactor,proto3" json:"branch_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnWorkflowTreeTask) Reset() {
	*x = SpawnWorkflowTreeTask{}
	mi := &file_examples_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnWorkflowTreeTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnWorkflowTreeTask) ProtoMessage() {}

func (x *SpawnWorkflowTreeTask) ProtoReflect() protoreflect.Message {
	mi := &file_examples_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnWorkflowTreeTask.ProtoReflect.Descriptor instead.
func (*SpawnWorkflowTreeTask) Descriptor() ([]byte, []int) {
	return file_examples_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *SpawnWorkflowTreeTask) GetCurrentLevel() int64 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *SpawnWorkflowTreeTask) GetDepth() int64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *SpawnWorkflowTreeTask) GetBranchFactor() int64 {
	if x != nil {
		return x.BranchFactor
	}
	return 0
}

var File_examples_v1_workflow_proto protoreflect.FileDescriptor

const file_examples_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1aexamples/v1/workflow.proto\x12\vexamples.v1\"w\n" +
	"\x15SpawnWorkflowTreeTask\x12#\n" +
	"\rcurrent_level\x18\x01 \x01(\x03R\fcurrentLevel\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x03R\x05depth\x12#\n" +
	"\rbranch_factor\x18\x03 \x01(\x03R\fbranchFactorB\xaf\x01\n" +
	"\x0fcom.examples.v1B\rWorkflowProtoP\x01Z@github.com/tilebox/tilebox-go/protogen/go/examples/v1;examplesv1\xa2\x02\x03EXX\xaa\x02\vExamples.V1\xca\x02\vExamples\\V1\xe2\x02\x17Examples\\V1\\GPBMetadata\xea\x02\fExamples::V1b\x06proto3"

var (
	file_examples_v1_workflow_proto_rawDescOnce sync.Once
	file_examples_v1_workflow_proto_rawDescData []byte
)

func file_examples_v1_workflow_proto_rawDescGZIP() []byte {
	file_examples_v1_workflow_proto_rawDescOnce.Do(func() {
		file_examples_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_v1_workflow_proto_rawDesc), len(file_examples_v1_workflow_proto_rawDesc)))
	})
	return file_examples_v1_workflow_proto_rawDescData
}

var file_examples_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_v1_workflow_proto_goTypes = []any{
	(*SpawnWorkflowTreeTask)(nil), // 0: examples.v1.SpawnWorkflowTreeTask
}
var file_examples_v1_workflow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_v1_workflow_proto_init() }
func file_examples_v1_workflow_proto_init() {
	if File_examples_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_v1_workflow_proto_rawDesc), len(file_examples_v1_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_v1_workflow_proto_goTypes,
		DependencyIndexes: file_examples_v1_workflow_proto_depIdxs,
		MessageInfos:      file_examples_v1_workflow_proto_msgTypes,
	}.Build()
	File_examples_v1_workflow_proto = out.File
	file_examples_v1_workflow_proto_goTypes = nil
	file_examples_v1_workflow_proto_depIdxs = nil
}
