// Public API for resolving account details associated with an authenticated request.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: accounts/v1alpha1/account.proto

package accountsv1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/tilebox/tilebox-go/protogen/accounts/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountServiceName is the fully-qualified name of the AccountService service.
	AccountServiceName = "accounts.v1alpha1.AccountService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountServiceGetAccountDetailsProcedure is the fully-qualified name of the AccountService's
	// GetAccountDetails RPC.
	AccountServiceGetAccountDetailsProcedure = "/accounts.v1alpha1.AccountService/GetAccountDetails"
)

// AccountServiceClient is a client for the accounts.v1alpha1.AccountService service.
type AccountServiceClient interface {
	// GetAccountDetails resolves the calling credential to its effective account details.
	// Requests without valid authentication fail with UNAUTHENTICATED.
	GetAccountDetails(context.Context, *connect.Request[v1alpha1.GetAccountDetailsRequest]) (*connect.Response[v1alpha1.AccountDetails], error)
}

// NewAccountServiceClient constructs a client for the accounts.v1alpha1.AccountService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accountServiceMethods := v1alpha1.File_accounts_v1alpha1_account_proto.Services().ByName("AccountService").Methods()
	return &accountServiceClient{
		getAccountDetails: connect.NewClient[v1alpha1.GetAccountDetailsRequest, v1alpha1.AccountDetails](
			httpClient,
			baseURL+AccountServiceGetAccountDetailsProcedure,
			connect.WithSchema(accountServiceMethods.ByName("GetAccountDetails")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountServiceClient implements AccountServiceClient.
type accountServiceClient struct {
	getAccountDetails *connect.Client[v1alpha1.GetAccountDetailsRequest, v1alpha1.AccountDetails]
}

// GetAccountDetails calls accounts.v1alpha1.AccountService.GetAccountDetails.
func (c *accountServiceClient) GetAccountDetails(ctx context.Context, req *connect.Request[v1alpha1.GetAccountDetailsRequest]) (*connect.Response[v1alpha1.AccountDetails], error) {
	return c.getAccountDetails.CallUnary(ctx, req)
}

// AccountServiceHandler is an implementation of the accounts.v1alpha1.AccountService service.
type AccountServiceHandler interface {
	// GetAccountDetails resolves the calling credential to its effective account details.
	// Requests without valid authentication fail with UNAUTHENTICATED.
	GetAccountDetails(context.Context, *connect.Request[v1alpha1.GetAccountDetailsRequest]) (*connect.Response[v1alpha1.AccountDetails], error)
}

// NewAccountServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountServiceHandler(svc AccountServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountServiceMethods := v1alpha1.File_accounts_v1alpha1_account_proto.Services().ByName("AccountService").Methods()
	accountServiceGetAccountDetailsHandler := connect.NewUnaryHandler(
		AccountServiceGetAccountDetailsProcedure,
		svc.GetAccountDetails,
		connect.WithSchema(accountServiceMethods.ByName("GetAccountDetails")),
		connect.WithHandlerOptions(opts...),
	)
	return "/accounts.v1alpha1.AccountService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountServiceGetAccountDetailsProcedure:
			accountServiceGetAccountDetailsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountServiceHandler struct{}

func (UnimplementedAccountServiceHandler) GetAccountDetails(context.Context, *connect.Request[v1alpha1.GetAccountDetailsRequest]) (*connect.Response[v1alpha1.AccountDetails], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("accounts.v1alpha1.AccountService.GetAccountDetails is not implemented"))
}
