// Public API for resolving the identity associated with an authenticated request.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: authentication/v1alpha1/authentication.proto

package authenticationv1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/tilebox/tilebox-go/protogen/authentication/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthenticationServiceName is the fully-qualified name of the AuthenticationService service.
	AuthenticationServiceName = "authentication.v1alpha1.AuthenticationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthenticationServiceGetAuthenticationStatusProcedure is the fully-qualified name of the
	// AuthenticationService's GetAuthenticationStatus RPC.
	AuthenticationServiceGetAuthenticationStatusProcedure = "/authentication.v1alpha1.AuthenticationService/GetAuthenticationStatus"
)

// AuthenticationServiceClient is a client for the authentication.v1alpha1.AuthenticationService
// service.
type AuthenticationServiceClient interface {
	// GetAuthenticationStatus resolves the calling credential to its effective user and organization.
	// Requests without valid authentication fail with UNAUTHENTICATED.
	GetAuthenticationStatus(context.Context, *connect.Request[v1alpha1.GetAuthenticationStatusRequest]) (*connect.Response[v1alpha1.AuthenticationStatus], error)
}

// NewAuthenticationServiceClient constructs a client for the
// authentication.v1alpha1.AuthenticationService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthenticationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthenticationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authenticationServiceMethods := v1alpha1.File_authentication_v1alpha1_authentication_proto.Services().ByName("AuthenticationService").Methods()
	return &authenticationServiceClient{
		getAuthenticationStatus: connect.NewClient[v1alpha1.GetAuthenticationStatusRequest, v1alpha1.AuthenticationStatus](
			httpClient,
			baseURL+AuthenticationServiceGetAuthenticationStatusProcedure,
			connect.WithSchema(authenticationServiceMethods.ByName("GetAuthenticationStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authenticationServiceClient implements AuthenticationServiceClient.
type authenticationServiceClient struct {
	getAuthenticationStatus *connect.Client[v1alpha1.GetAuthenticationStatusRequest, v1alpha1.AuthenticationStatus]
}

// GetAuthenticationStatus calls
// authentication.v1alpha1.AuthenticationService.GetAuthenticationStatus.
func (c *authenticationServiceClient) GetAuthenticationStatus(ctx context.Context, req *connect.Request[v1alpha1.GetAuthenticationStatusRequest]) (*connect.Response[v1alpha1.AuthenticationStatus], error) {
	return c.getAuthenticationStatus.CallUnary(ctx, req)
}

// AuthenticationServiceHandler is an implementation of the
// authentication.v1alpha1.AuthenticationService service.
type AuthenticationServiceHandler interface {
	// GetAuthenticationStatus resolves the calling credential to its effective user and organization.
	// Requests without valid authentication fail with UNAUTHENTICATED.
	GetAuthenticationStatus(context.Context, *connect.Request[v1alpha1.GetAuthenticationStatusRequest]) (*connect.Response[v1alpha1.AuthenticationStatus], error)
}

// NewAuthenticationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthenticationServiceHandler(svc AuthenticationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authenticationServiceMethods := v1alpha1.File_authentication_v1alpha1_authentication_proto.Services().ByName("AuthenticationService").Methods()
	authenticationServiceGetAuthenticationStatusHandler := connect.NewUnaryHandler(
		AuthenticationServiceGetAuthenticationStatusProcedure,
		svc.GetAuthenticationStatus,
		connect.WithSchema(authenticationServiceMethods.ByName("GetAuthenticationStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/authentication.v1alpha1.AuthenticationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthenticationServiceGetAuthenticationStatusProcedure:
			authenticationServiceGetAuthenticationStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthenticationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthenticationServiceHandler struct{}

func (UnimplementedAuthenticationServiceHandler) GetAuthenticationStatus(context.Context, *connect.Request[v1alpha1.GetAuthenticationStatusRequest]) (*connect.Response[v1alpha1.AuthenticationStatus], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authentication.v1alpha1.AuthenticationService.GetAuthenticationStatus is not implemented"))
}
