// The externally facing API allowing users to publish and deploy workflow task releases.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflows/v1/task_release.proto

package workflowsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/tilebox/tilebox-go/protogen/tilebox/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishReleaseRequest publishes immutable release metadata for a release task set.
type PublishReleaseRequest struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tasks             *[]*TaskIdentifier     `protobuf:"bytes,1,rep,name=tasks"`
	xxx_hidden_ArtifactUri       string                 `protobuf:"bytes,2,opt,name=artifact_uri,json=artifactUri"`
	xxx_hidden_ArtifactDigest    string                 `protobuf:"bytes,3,opt,name=artifact_digest,json=artifactDigest"`
	xxx_hidden_RuntimeKind       string                 `protobuf:"bytes,4,opt,name=runtime_kind,json=runtimeKind"`
	xxx_hidden_EnvironmentDigest string                 `protobuf:"bytes,5,opt,name=environment_digest,json=environmentDigest"`
	xxx_hidden_MetadataJson      []byte                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *PublishReleaseRequest) Reset() {
	*x = PublishReleaseRequest{}
	mi := &file_workflows_v1_task_release_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReleaseRequest) ProtoMessage() {}

func (x *PublishReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_task_release_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublishReleaseRequest) GetTasks() []*TaskIdentifier {
	if x != nil {
		if x.xxx_hidden_Tasks != nil {
			return *x.xxx_hidden_Tasks
		}
	}
	return nil
}

func (x *PublishReleaseRequest) GetArtifactUri() string {
	if x != nil {
		return x.xxx_hidden_ArtifactUri
	}
	return ""
}

func (x *PublishReleaseRequest) GetArtifactDigest() string {
	if x != nil {
		return x.xxx_hidden_ArtifactDigest
	}
	return ""
}

func (x *PublishReleaseRequest) GetRuntimeKind() string {
	if x != nil {
		return x.xxx_hidden_RuntimeKind
	}
	return ""
}

func (x *PublishReleaseRequest) GetEnvironmentDigest() string {
	if x != nil {
		return x.xxx_hidden_EnvironmentDigest
	}
	return ""
}

func (x *PublishReleaseRequest) GetMetadataJson() []byte {
	if x != nil {
		return x.xxx_hidden_MetadataJson
	}
	return nil
}

func (x *PublishReleaseRequest) SetTasks(v []*TaskIdentifier) {
	x.xxx_hidden_Tasks = &v
}

func (x *PublishReleaseRequest) SetArtifactUri(v string) {
	x.xxx_hidden_ArtifactUri = v
}

func (x *PublishReleaseRequest) SetArtifactDigest(v string) {
	x.xxx_hidden_ArtifactDigest = v
}

func (x *PublishReleaseRequest) SetRuntimeKind(v string) {
	x.xxx_hidden_RuntimeKind = v
}

func (x *PublishReleaseRequest) SetEnvironmentDigest(v string) {
	x.xxx_hidden_EnvironmentDigest = v
}

func (x *PublishReleaseRequest) SetMetadataJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MetadataJson = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *PublishReleaseRequest) HasMetadataJson() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PublishReleaseRequest) ClearMetadataJson() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_MetadataJson = nil
}

type PublishReleaseRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Task identifiers included in this release.
	Tasks []*TaskIdentifier
	// URI pointing to the release artifact.
	ArtifactUri string
	// Canonical artifact digest in format sha256:<hex>.
	ArtifactDigest string
	// Runtime kind for this release, currently python_uv in phase 1.
	RuntimeKind string
	// Canonical environment digest in format sha256:<hex>.
	EnvironmentDigest string
	// Optional UTF-8 JSON metadata payload.
	MetadataJson []byte
}

func (b0 PublishReleaseRequest_builder) Build() *PublishReleaseRequest {
	m0 := &PublishReleaseRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Tasks = &b.Tasks
	x.xxx_hidden_ArtifactUri = b.ArtifactUri
	x.xxx_hidden_ArtifactDigest = b.ArtifactDigest
	x.xxx_hidden_RuntimeKind = b.RuntimeKind
	x.xxx_hidden_EnvironmentDigest = b.EnvironmentDigest
	if b.MetadataJson != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_MetadataJson = b.MetadataJson
	}
	return m0
}

// PublishReleaseResponse is the publish API response.
type PublishReleaseResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ReleaseId *v1.ID                 `protobuf:"bytes,1,opt,name=release_id,json=releaseId"`
	xxx_hidden_Created   bool                   `protobuf:"varint,2,opt,name=created"`
	xxx_hidden_Changes   *PublishReleaseChanges `protobuf:"bytes,4,opt,name=changes"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PublishReleaseResponse) Reset() {
	*x = PublishReleaseResponse{}
	mi := &file_workflows_v1_task_release_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReleaseResponse) ProtoMessage() {}

func (x *PublishReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_task_release_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublishReleaseResponse) GetReleaseId() *v1.ID {
	if x != nil {
		return x.xxx_hidden_ReleaseId
	}
	return nil
}

func (x *PublishReleaseResponse) GetCreated() bool {
	if x != nil {
		return x.xxx_hidden_Created
	}
	return false
}

func (x *PublishReleaseResponse) GetChanges() *PublishReleaseChanges {
	if x != nil {
		return x.xxx_hidden_Changes
	}
	return nil
}

func (x *PublishReleaseResponse) SetReleaseId(v *v1.ID) {
	x.xxx_hidden_ReleaseId = v
}

func (x *PublishReleaseResponse) SetCreated(v bool) {
	x.xxx_hidden_Created = v
}

func (x *PublishReleaseResponse) SetChanges(v *PublishReleaseChanges) {
	x.xxx_hidden_Changes = v
}

func (x *PublishReleaseResponse) HasReleaseId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReleaseId != nil
}

func (x *PublishReleaseResponse) HasChanges() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Changes != nil
}

func (x *PublishReleaseResponse) ClearReleaseId() {
	x.xxx_hidden_ReleaseId = nil
}

func (x *PublishReleaseResponse) ClearChanges() {
	x.xxx_hidden_Changes = nil
}

type PublishReleaseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Immutable release id.
	ReleaseId *v1.ID
	// True when this call created a new release row.
	Created bool
	// Explicit payload changes compared to the latest comparable release.
	Changes *PublishReleaseChanges
}

func (b0 PublishReleaseResponse_builder) Build() *PublishReleaseResponse {
	m0 := &PublishReleaseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ReleaseId = b.ReleaseId
	x.xxx_hidden_Created = b.Created
	x.xxx_hidden_Changes = b.Changes
	return m0
}

// PublishReleaseChanges captures which release surfaces changed.
type PublishReleaseChanges struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Tasks       bool                   `protobuf:"varint,1,opt,name=tasks"`
	xxx_hidden_Artifact    bool                   `protobuf:"varint,2,opt,name=artifact"`
	xxx_hidden_Environment bool                   `protobuf:"varint,3,opt,name=environment"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PublishReleaseChanges) Reset() {
	*x = PublishReleaseChanges{}
	mi := &file_workflows_v1_task_release_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReleaseChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReleaseChanges) ProtoMessage() {}

func (x *PublishReleaseChanges) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_task_release_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublishReleaseChanges) GetTasks() bool {
	if x != nil {
		return x.xxx_hidden_Tasks
	}
	return false
}

func (x *PublishReleaseChanges) GetArtifact() bool {
	if x != nil {
		return x.xxx_hidden_Artifact
	}
	return false
}

func (x *PublishReleaseChanges) GetEnvironment() bool {
	if x != nil {
		return x.xxx_hidden_Environment
	}
	return false
}

func (x *PublishReleaseChanges) SetTasks(v bool) {
	x.xxx_hidden_Tasks = v
}

func (x *PublishReleaseChanges) SetArtifact(v bool) {
	x.xxx_hidden_Artifact = v
}

func (x *PublishReleaseChanges) SetEnvironment(v bool) {
	x.xxx_hidden_Environment = v
}

type PublishReleaseChanges_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// True when the task set (including versions) changed.
	Tasks bool
	// True when the artifact content changed.
	Artifact bool
	// True when the runtime environment changed.
	Environment bool
}

func (b0 PublishReleaseChanges_builder) Build() *PublishReleaseChanges {
	m0 := &PublishReleaseChanges{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Tasks = b.Tasks
	x.xxx_hidden_Artifact = b.Artifact
	x.xxx_hidden_Environment = b.Environment
	return m0
}

// DeployReleaseRequest updates the cluster deployment pointer for a release.
type DeployReleaseRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClusterSlug string                 `protobuf:"bytes,1,opt,name=cluster_slug,json=clusterSlug"`
	xxx_hidden_ReleaseId   *v1.ID                 `protobuf:"bytes,2,opt,name=release_id,json=releaseId"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeployReleaseRequest) Reset() {
	*x = DeployReleaseRequest{}
	mi := &file_workflows_v1_task_release_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployReleaseRequest) ProtoMessage() {}

func (x *DeployReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_task_release_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeployReleaseRequest) GetClusterSlug() string {
	if x != nil {
		return x.xxx_hidden_ClusterSlug
	}
	return ""
}

func (x *DeployReleaseRequest) GetReleaseId() *v1.ID {
	if x != nil {
		return x.xxx_hidden_ReleaseId
	}
	return nil
}

func (x *DeployReleaseRequest) SetClusterSlug(v string) {
	x.xxx_hidden_ClusterSlug = v
}

func (x *DeployReleaseRequest) SetReleaseId(v *v1.ID) {
	x.xxx_hidden_ReleaseId = v
}

func (x *DeployReleaseRequest) HasReleaseId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReleaseId != nil
}

func (x *DeployReleaseRequest) ClearReleaseId() {
	x.xxx_hidden_ReleaseId = nil
}

type DeployReleaseRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Target cluster slug.
	ClusterSlug string
	// Immutable release id.
	ReleaseId *v1.ID
}

func (b0 DeployReleaseRequest_builder) Build() *DeployReleaseRequest {
	m0 := &DeployReleaseRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ClusterSlug = b.ClusterSlug
	x.xxx_hidden_ReleaseId = b.ReleaseId
	return m0
}

// DeployReleaseResponse is the deploy API response.
type DeployReleaseResponse struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClusterSlug      string                 `protobuf:"bytes,1,opt,name=cluster_slug,json=clusterSlug"`
	xxx_hidden_ReleaseId        *v1.ID                 `protobuf:"bytes,2,opt,name=release_id,json=releaseId"`
	xxx_hidden_ManifestRevision uint64                 `protobuf:"varint,3,opt,name=manifest_revision,json=manifestRevision"`
	xxx_hidden_Changed          bool                   `protobuf:"varint,4,opt,name=changed"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DeployReleaseResponse) Reset() {
	*x = DeployReleaseResponse{}
	mi := &file_workflows_v1_task_release_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployReleaseResponse) ProtoMessage() {}

func (x *DeployReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_task_release_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeployReleaseResponse) GetClusterSlug() string {
	if x != nil {
		return x.xxx_hidden_ClusterSlug
	}
	return ""
}

func (x *DeployReleaseResponse) GetReleaseId() *v1.ID {
	if x != nil {
		return x.xxx_hidden_ReleaseId
	}
	return nil
}

func (x *DeployReleaseResponse) GetManifestRevision() uint64 {
	if x != nil {
		return x.xxx_hidden_ManifestRevision
	}
	return 0
}

func (x *DeployReleaseResponse) GetChanged() bool {
	if x != nil {
		return x.xxx_hidden_Changed
	}
	return false
}

func (x *DeployReleaseResponse) SetClusterSlug(v string) {
	x.xxx_hidden_ClusterSlug = v
}

func (x *DeployReleaseResponse) SetReleaseId(v *v1.ID) {
	x.xxx_hidden_ReleaseId = v
}

func (x *DeployReleaseResponse) SetManifestRevision(v uint64) {
	x.xxx_hidden_ManifestRevision = v
}

func (x *DeployReleaseResponse) SetChanged(v bool) {
	x.xxx_hidden_Changed = v
}

func (x *DeployReleaseResponse) HasReleaseId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReleaseId != nil
}

func (x *DeployReleaseResponse) ClearReleaseId() {
	x.xxx_hidden_ReleaseId = nil
}

type DeployReleaseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Target cluster slug.
	ClusterSlug string
	// Deployed release id.
	ReleaseId *v1.ID
	// Latest cluster manifest revision after the request.
	ManifestRevision uint64
	// Whether this request changed the deployment pointer.
	Changed bool
}

func (b0 DeployReleaseResponse_builder) Build() *DeployReleaseResponse {
	m0 := &DeployReleaseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ClusterSlug = b.ClusterSlug
	x.xxx_hidden_ReleaseId = b.ReleaseId
	x.xxx_hidden_ManifestRevision = b.ManifestRevision
	x.xxx_hidden_Changed = b.Changed
	return m0
}

// GetClusterDeploymentManifestRequest requests the active desired state for a cluster.
type GetClusterDeploymentManifestRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClusterSlug   string                 `protobuf:"bytes,1,opt,name=cluster_slug,json=clusterSlug"`
	xxx_hidden_SinceRevision uint64                 `protobuf:"varint,2,opt,name=since_revision,json=sinceRevision"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetClusterDeploymentManifestRequest) Reset() {
	*x = GetClusterDeploymentManifestRequest{}
	mi := &file_workflows_v1_task_release_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterDeploymentManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterDeploymentManifestRequest) ProtoMessage() {}

func (x *GetClusterDeploymentManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_task_release_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetClusterDeploymentManifestRequest) GetClusterSlug() string {
	if x != nil {
		return x.xxx_hidden_ClusterSlug
	}
	return ""
}

func (x *GetClusterDeploymentManifestRequest) GetSinceRevision() uint64 {
	if x != nil {
		return x.xxx_hidden_SinceRevision
	}
	return 0
}

func (x *GetClusterDeploymentManifestRequest) SetClusterSlug(v string) {
	x.xxx_hidden_ClusterSlug = v
}

func (x *GetClusterDeploymentManifestRequest) SetSinceRevision(v uint64) {
	x.xxx_hidden_SinceRevision = v
}

type GetClusterDeploymentManifestRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Target cluster slug.
	ClusterSlug string
	// Optional revision cursor. 0 requests a full snapshot.
	SinceRevision uint64
}

func (b0 GetClusterDeploymentManifestRequest_builder) Build() *GetClusterDeploymentManifestRequest {
	m0 := &GetClusterDeploymentManifestRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ClusterSlug = b.ClusterSlug
	x.xxx_hidden_SinceRevision = b.SinceRevision
	return m0
}

// DeployedRelease describes the currently deployed release in the manifest response.
type DeployedRelease struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ReleaseId         *v1.ID                 `protobuf:"bytes,1,opt,name=release_id,json=releaseId"`
	xxx_hidden_ArtifactUri       string                 `protobuf:"bytes,2,opt,name=artifact_uri,json=artifactUri"`
	xxx_hidden_ArtifactDigest    string                 `protobuf:"bytes,3,opt,name=artifact_digest,json=artifactDigest"`
	xxx_hidden_RuntimeKind       string                 `protobuf:"bytes,4,opt,name=runtime_kind,json=runtimeKind"`
	xxx_hidden_EnvironmentDigest string                 `protobuf:"bytes,5,opt,name=environment_digest,json=environmentDigest"`
	xxx_hidden_MetadataJson      []byte                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson"`
	xxx_hidden_ChangeRevision    uint64                 `protobuf:"varint,7,opt,name=change_revision,json=changeRevision"`
	xxx_hidden_Tasks             *[]*TaskIdentifier     `protobuf:"bytes,8,rep,name=tasks"`
	xxx_hidden_DeployedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deployed_at,json=deployedAt"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DeployedRelease) Reset() {
	*x = DeployedRelease{}
	mi := &file_workflows_v1_task_release_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployedRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployedRelease) ProtoMessage() {}

func (x *DeployedRelease) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_task_release_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeployedRelease) GetReleaseId() *v1.ID {
	if x != nil {
		return x.xxx_hidden_ReleaseId
	}
	return nil
}

func (x *DeployedRelease) GetArtifactUri() string {
	if x != nil {
		return x.xxx_hidden_ArtifactUri
	}
	return ""
}

func (x *DeployedRelease) GetArtifactDigest() string {
	if x != nil {
		return x.xxx_hidden_ArtifactDigest
	}
	return ""
}

func (x *DeployedRelease) GetRuntimeKind() string {
	if x != nil {
		return x.xxx_hidden_RuntimeKind
	}
	return ""
}

func (x *DeployedRelease) GetEnvironmentDigest() string {
	if x != nil {
		return x.xxx_hidden_EnvironmentDigest
	}
	return ""
}

func (x *DeployedRelease) GetMetadataJson() []byte {
	if x != nil {
		return x.xxx_hidden_MetadataJson
	}
	return nil
}

func (x *DeployedRelease) GetChangeRevision() uint64 {
	if x != nil {
		return x.xxx_hidden_ChangeRevision
	}
	return 0
}

func (x *DeployedRelease) GetTasks() []*TaskIdentifier {
	if x != nil {
		if x.xxx_hidden_Tasks != nil {
			return *x.xxx_hidden_Tasks
		}
	}
	return nil
}

func (x *DeployedRelease) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeployedAt
	}
	return nil
}

func (x *DeployedRelease) SetReleaseId(v *v1.ID) {
	x.xxx_hidden_ReleaseId = v
}

func (x *DeployedRelease) SetArtifactUri(v string) {
	x.xxx_hidden_ArtifactUri = v
}

func (x *DeployedRelease) SetArtifactDigest(v string) {
	x.xxx_hidden_ArtifactDigest = v
}

func (x *DeployedRelease) SetRuntimeKind(v string) {
	x.xxx_hidden_RuntimeKind = v
}

func (x *DeployedRelease) SetEnvironmentDigest(v string) {
	x.xxx_hidden_EnvironmentDigest = v
}

func (x *DeployedRelease) SetMetadataJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_MetadataJson = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *DeployedRelease) SetChangeRevision(v uint64) {
	x.xxx_hidden_ChangeRevision = v
}

func (x *DeployedRelease) SetTasks(v []*TaskIdentifier) {
	x.xxx_hidden_Tasks = &v
}

func (x *DeployedRelease) SetDeployedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeployedAt = v
}

func (x *DeployedRelease) HasReleaseId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ReleaseId != nil
}

func (x *DeployedRelease) HasMetadataJson() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *DeployedRelease) HasDeployedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeployedAt != nil
}

func (x *DeployedRelease) ClearReleaseId() {
	x.xxx_hidden_ReleaseId = nil
}

func (x *DeployedRelease) ClearMetadataJson() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_MetadataJson = nil
}

func (x *DeployedRelease) ClearDeployedAt() {
	x.xxx_hidden_DeployedAt = nil
}

type DeployedRelease_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Immutable release id.
	ReleaseId *v1.ID
	// URI pointing to the release artifact.
	ArtifactUri string
	// Canonical artifact digest.
	ArtifactDigest string
	// Runtime kind.
	RuntimeKind string
	// Canonical environment digest.
	EnvironmentDigest string
	// Optional UTF-8 JSON metadata payload.
	MetadataJson []byte
	// Deployment revision at which this release pointer changed.
	ChangeRevision uint64
	// Task identifiers included in the deployed release.
	Tasks []*TaskIdentifier
	// Timestamp when this release pointer was deployed.
	DeployedAt *timestamppb.Timestamp
}

func (b0 DeployedRelease_builder) Build() *DeployedRelease {
	m0 := &DeployedRelease{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ReleaseId = b.ReleaseId
	x.xxx_hidden_ArtifactUri = b.ArtifactUri
	x.xxx_hidden_ArtifactDigest = b.ArtifactDigest
	x.xxx_hidden_RuntimeKind = b.RuntimeKind
	x.xxx_hidden_EnvironmentDigest = b.EnvironmentDigest
	if b.MetadataJson != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_MetadataJson = b.MetadataJson
	}
	x.xxx_hidden_ChangeRevision = b.ChangeRevision
	x.xxx_hidden_Tasks = &b.Tasks
	x.xxx_hidden_DeployedAt = b.DeployedAt
	return m0
}

// GetClusterDeploymentManifestResponse returns desired deployment state for a cluster.
type GetClusterDeploymentManifestResponse struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClusterSlug      string                 `protobuf:"bytes,1,opt,name=cluster_slug,json=clusterSlug"`
	xxx_hidden_ManifestRevision uint64                 `protobuf:"varint,2,opt,name=manifest_revision,json=manifestRevision"`
	xxx_hidden_Release          *DeployedRelease       `protobuf:"bytes,3,opt,name=release"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GetClusterDeploymentManifestResponse) Reset() {
	*x = GetClusterDeploymentManifestResponse{}
	mi := &file_workflows_v1_task_release_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterDeploymentManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterDeploymentManifestResponse) ProtoMessage() {}

func (x *GetClusterDeploymentManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_task_release_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetClusterDeploymentManifestResponse) GetClusterSlug() string {
	if x != nil {
		return x.xxx_hidden_ClusterSlug
	}
	return ""
}

func (x *GetClusterDeploymentManifestResponse) GetManifestRevision() uint64 {
	if x != nil {
		return x.xxx_hidden_ManifestRevision
	}
	return 0
}

func (x *GetClusterDeploymentManifestResponse) GetRelease() *DeployedRelease {
	if x != nil {
		return x.xxx_hidden_Release
	}
	return nil
}

func (x *GetClusterDeploymentManifestResponse) SetClusterSlug(v string) {
	x.xxx_hidden_ClusterSlug = v
}

func (x *GetClusterDeploymentManifestResponse) SetManifestRevision(v uint64) {
	x.xxx_hidden_ManifestRevision = v
}

func (x *GetClusterDeploymentManifestResponse) SetRelease(v *DeployedRelease) {
	x.xxx_hidden_Release = v
}

func (x *GetClusterDeploymentManifestResponse) HasRelease() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Release != nil
}

func (x *GetClusterDeploymentManifestResponse) ClearRelease() {
	x.xxx_hidden_Release = nil
}

type GetClusterDeploymentManifestResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Target cluster slug.
	ClusterSlug string
	// Latest cluster manifest revision.
	ManifestRevision uint64
	// Active deployed release. Empty when nothing is deployed or when unchanged since since_revision.
	Release *DeployedRelease
}

func (b0 GetClusterDeploymentManifestResponse_builder) Build() *GetClusterDeploymentManifestResponse {
	m0 := &GetClusterDeploymentManifestResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ClusterSlug = b.ClusterSlug
	x.xxx_hidden_ManifestRevision = b.ManifestRevision
	x.xxx_hidden_Release = b.Release
	return m0
}

var File_workflows_v1_task_release_proto protoreflect.FileDescriptor

const file_workflows_v1_task_release_proto_rawDesc = "" +
	"\n" +
	"\x1fworkflows/v1/task_release.proto\x12\fworkflows.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13tilebox/v1/id.proto\x1a\x17workflows/v1/core.proto\"\xed\x02\n" +
	"\x15PublishReleaseRequest\x12<\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1c.workflows.v1.TaskIdentifierB\b\xbaH\x05\x92\x01\x02\b\x01R\x05tasks\x12*\n" +
	"\fartifact_uri\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vartifactUri\x12E\n" +
	"\x0fartifact_digest\x18\x03 \x01(\tB\x1c\xbaH\x19r\x172\x15^sha256:[a-f0-9]{64}$R\x0eartifactDigest\x12*\n" +
	"\fruntime_kind\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vruntimeKind\x12K\n" +
	"\x12environment_digest\x18\x05 \x01(\tB\x1c\xbaH\x19r\x172\x15^sha256:[a-f0-9]{64}$R\x11environmentDigest\x12*\n" +
	"\rmetadata_json\x18\x06 \x01(\fB\x05\xaa\x01\x02\b\x01R\fmetadataJson\"\xb2\x01\n" +
	"\x16PublishReleaseResponse\x12-\n" +
	"\n" +
	"release_id\x18\x01 \x01(\v2\x0e.tilebox.v1.IDR\treleaseId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\x12=\n" +
	"\achanges\x18\x04 \x01(\v2#.workflows.v1.PublishReleaseChangesR\achangesJ\x04\b\x03\x10\x04R\n" +
	"idempotent\"k\n" +
	"\x15PublishReleaseChanges\x12\x14\n" +
	"\x05tasks\x18\x01 \x01(\bR\x05tasks\x12\x1a\n" +
	"\bartifact\x18\x02 \x01(\bR\bartifact\x12 \n" +
	"\venvironment\x18\x03 \x01(\bR\venvironment\"y\n" +
	"\x14DeployReleaseRequest\x12*\n" +
	"\fcluster_slug\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vclusterSlug\x125\n" +
	"\n" +
	"release_id\x18\x02 \x01(\v2\x0e.tilebox.v1.IDB\x06\xbaH\x03\xc8\x01\x01R\treleaseId\"\xb0\x01\n" +
	"\x15DeployReleaseResponse\x12!\n" +
	"\fcluster_slug\x18\x01 \x01(\tR\vclusterSlug\x12-\n" +
	"\n" +
	"release_id\x18\x02 \x01(\v2\x0e.tilebox.v1.IDR\treleaseId\x12+\n" +
	"\x11manifest_revision\x18\x03 \x01(\x04R\x10manifestRevision\x12\x18\n" +
	"\achanged\x18\x04 \x01(\bR\achanged\"x\n" +
	"#GetClusterDeploymentManifestRequest\x12*\n" +
	"\fcluster_slug\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vclusterSlug\x12%\n" +
	"\x0esince_revision\x18\x02 \x01(\x04R\rsinceRevision\"\xa4\x03\n" +
	"\x0fDeployedRelease\x12-\n" +
	"\n" +
	"release_id\x18\x01 \x01(\v2\x0e.tilebox.v1.IDR\treleaseId\x12!\n" +
	"\fartifact_uri\x18\x02 \x01(\tR\vartifactUri\x12'\n" +
	"\x0fartifact_digest\x18\x03 \x01(\tR\x0eartifactDigest\x12!\n" +
	"\fruntime_kind\x18\x04 \x01(\tR\vruntimeKind\x12-\n" +
	"\x12environment_digest\x18\x05 \x01(\tR\x11environmentDigest\x12*\n" +
	"\rmetadata_json\x18\x06 \x01(\fB\x05\xaa\x01\x02\b\x01R\fmetadataJson\x12'\n" +
	"\x0fchange_revision\x18\a \x01(\x04R\x0echangeRevision\x122\n" +
	"\x05tasks\x18\b \x03(\v2\x1c.workflows.v1.TaskIdentifierR\x05tasks\x12;\n" +
	"\vdeployed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\"\xaf\x01\n" +
	"$GetClusterDeploymentManifestResponse\x12!\n" +
	"\fcluster_slug\x18\x01 \x01(\tR\vclusterSlug\x12+\n" +
	"\x11manifest_revision\x18\x02 \x01(\x04R\x10manifestRevision\x127\n" +
	"\arelease\x18\x03 \x01(\v2\x1d.workflows.v1.DeployedReleaseR\arelease2\xd3\x02\n" +
	"\x12TaskReleaseService\x12[\n" +
	"\x0ePublishRelease\x12#.workflows.v1.PublishReleaseRequest\x1a$.workflows.v1.PublishReleaseResponse\x12X\n" +
	"\rDeployRelease\x12\".workflows.v1.DeployReleaseRequest\x1a#.workflows.v1.DeployReleaseResponse\x12\x85\x01\n" +
	"\x1cGetClusterDeploymentManifest\x121.workflows.v1.GetClusterDeploymentManifestRequest\x1a2.workflows.v1.GetClusterDeploymentManifestResponseB\xbb\x01\n" +
	"\x10com.workflows.v1B\x10TaskReleaseProtoP\x01Z?github.com/tilebox/tilebox-go/protogen/workflows/v1;workflowsv1\xa2\x02\x03WXX\xaa\x02\fWorkflows.V1\xca\x02\fWorkflows\\V1\xe2\x02\x18Workflows\\V1\\GPBMetadata\xea\x02\rWorkflows::V1\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_workflows_v1_task_release_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_workflows_v1_task_release_proto_goTypes = []any{
	(*PublishReleaseRequest)(nil),                // 0: workflows.v1.PublishReleaseRequest
	(*PublishReleaseResponse)(nil),               // 1: workflows.v1.PublishReleaseResponse
	(*PublishReleaseChanges)(nil),                // 2: workflows.v1.PublishReleaseChanges
	(*DeployReleaseRequest)(nil),                 // 3: workflows.v1.DeployReleaseRequest
	(*DeployReleaseResponse)(nil),                // 4: workflows.v1.DeployReleaseResponse
	(*GetClusterDeploymentManifestRequest)(nil),  // 5: workflows.v1.GetClusterDeploymentManifestRequest
	(*DeployedRelease)(nil),                      // 6: workflows.v1.DeployedRelease
	(*GetClusterDeploymentManifestResponse)(nil), // 7: workflows.v1.GetClusterDeploymentManifestResponse
	(*TaskIdentifier)(nil),                       // 8: workflows.v1.TaskIdentifier
	(*v1.ID)(nil),                                // 9: tilebox.v1.ID
	(*timestamppb.Timestamp)(nil),                // 10: google.protobuf.Timestamp
}
var file_workflows_v1_task_release_proto_depIdxs = []int32{
	8,  // 0: workflows.v1.PublishReleaseRequest.tasks:type_name -> workflows.v1.TaskIdentifier
	9,  // 1: workflows.v1.PublishReleaseResponse.release_id:type_name -> tilebox.v1.ID
	2,  // 2: workflows.v1.PublishReleaseResponse.changes:type_name -> workflows.v1.PublishReleaseChanges
	9,  // 3: workflows.v1.DeployReleaseRequest.release_id:type_name -> tilebox.v1.ID
	9,  // 4: workflows.v1.DeployReleaseResponse.release_id:type_name -> tilebox.v1.ID
	9,  // 5: workflows.v1.DeployedRelease.release_id:type_name -> tilebox.v1.ID
	8,  // 6: workflows.v1.DeployedRelease.tasks:type_name -> workflows.v1.TaskIdentifier
	10, // 7: workflows.v1.DeployedRelease.deployed_at:type_name -> google.protobuf.Timestamp
	6,  // 8: workflows.v1.GetClusterDeploymentManifestResponse.release:type_name -> workflows.v1.DeployedRelease
	0,  // 9: workflows.v1.TaskReleaseService.PublishRelease:input_type -> workflows.v1.PublishReleaseRequest
	3,  // 10: workflows.v1.TaskReleaseService.DeployRelease:input_type -> workflows.v1.DeployReleaseRequest
	5,  // 11: workflows.v1.TaskReleaseService.GetClusterDeploymentManifest:input_type -> workflows.v1.GetClusterDeploymentManifestRequest
	1,  // 12: workflows.v1.TaskReleaseService.PublishRelease:output_type -> workflows.v1.PublishReleaseResponse
	4,  // 13: workflows.v1.TaskReleaseService.DeployRelease:output_type -> workflows.v1.DeployReleaseResponse
	7,  // 14: workflows.v1.TaskReleaseService.GetClusterDeploymentManifest:output_type -> workflows.v1.GetClusterDeploymentManifestResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_workflows_v1_task_release_proto_init() }
func file_workflows_v1_task_release_proto_init() {
	if File_workflows_v1_task_release_proto != nil {
		return
	}
	file_workflows_v1_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflows_v1_task_release_proto_rawDesc), len(file_workflows_v1_task_release_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflows_v1_task_release_proto_goTypes,
		DependencyIndexes: file_workflows_v1_task_release_proto_depIdxs,
		MessageInfos:      file_workflows_v1_task_release_proto_msgTypes,
	}.Build()
	File_workflows_v1_task_release_proto = out.File
	file_workflows_v1_task_release_proto_goTypes = nil
	file_workflows_v1_task_release_proto_depIdxs = nil
}
