// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflows/v1/telemetry.proto

package workflowsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/tilebox/tilebox-go/protogen/tilebox/v1"
	v11 "go.opentelemetry.io/proto/otlp/logs/v1"
	v12 "go.opentelemetry.io/proto/otlp/trace/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryJobLogsRequest is the request message for querying logs of a specific job, in ascending or descending order,
// with pagination support.
type QueryJobLogsRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_JobId         *v1.ID                 `protobuf:"bytes,1,opt,name=job_id,json=jobId"`
	xxx_hidden_Page          *v1.Pagination         `protobuf:"bytes,2,opt,name=page"`
	xxx_hidden_SortDirection v1.SortDirection       `protobuf:"varint,3,opt,name=sort_direction,json=sortDirection,enum=tilebox.v1.SortDirection"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *QueryJobLogsRequest) Reset() {
	*x = QueryJobLogsRequest{}
	mi := &file_workflows_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJobLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJobLogsRequest) ProtoMessage() {}

func (x *QueryJobLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryJobLogsRequest) GetJobId() *v1.ID {
	if x != nil {
		return x.xxx_hidden_JobId
	}
	return nil
}

func (x *QueryJobLogsRequest) GetPage() *v1.Pagination {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *QueryJobLogsRequest) GetSortDirection() v1.SortDirection {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_SortDirection
		}
	}
	return v1.SortDirection(0)
}

func (x *QueryJobLogsRequest) SetJobId(v *v1.ID) {
	x.xxx_hidden_JobId = v
}

func (x *QueryJobLogsRequest) SetPage(v *v1.Pagination) {
	x.xxx_hidden_Page = v
}

func (x *QueryJobLogsRequest) SetSortDirection(v v1.SortDirection) {
	x.xxx_hidden_SortDirection = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *QueryJobLogsRequest) HasJobId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_JobId != nil
}

func (x *QueryJobLogsRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *QueryJobLogsRequest) HasSortDirection() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *QueryJobLogsRequest) ClearJobId() {
	x.xxx_hidden_JobId = nil
}

func (x *QueryJobLogsRequest) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *QueryJobLogsRequest) ClearSortDirection() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SortDirection = v1.SortDirection_SORT_DIRECTION_UNSPECIFIED
}

type QueryJobLogsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the job to query logs for.
	JobId *v1.ID
	// The pagination parameters for this request.
	Page *v1.Pagination
	// The direction in which to sort log entries. If not specified, defaults to ascending order (oldest entries first).
	SortDirection *v1.SortDirection
}

func (b0 QueryJobLogsRequest_builder) Build() *QueryJobLogsRequest {
	m0 := &QueryJobLogsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_JobId = b.JobId
	x.xxx_hidden_Page = b.Page
	if b.SortDirection != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_SortDirection = *b.SortDirection
	}
	return m0
}

// QueryLogsInIntervalRequest is the request message for querying logs in a specific time interval.
// It can be used to query all log messages across multiple jobs, and can be filtered by other parameters in the future.
type QueryLogsInIntervalRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TimeInterval  *v1.TimeInterval       `protobuf:"bytes,1,opt,name=time_interval,json=timeInterval"`
	xxx_hidden_Page          *v1.Pagination         `protobuf:"bytes,2,opt,name=page"`
	xxx_hidden_SortDirection v1.SortDirection       `protobuf:"varint,3,opt,name=sort_direction,json=sortDirection,enum=tilebox.v1.SortDirection"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *QueryLogsInIntervalRequest) Reset() {
	*x = QueryLogsInIntervalRequest{}
	mi := &file_workflows_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsInIntervalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsInIntervalRequest) ProtoMessage() {}

func (x *QueryLogsInIntervalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryLogsInIntervalRequest) GetTimeInterval() *v1.TimeInterval {
	if x != nil {
		return x.xxx_hidden_TimeInterval
	}
	return nil
}

func (x *QueryLogsInIntervalRequest) GetPage() *v1.Pagination {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *QueryLogsInIntervalRequest) GetSortDirection() v1.SortDirection {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_SortDirection
		}
	}
	return v1.SortDirection(0)
}

func (x *QueryLogsInIntervalRequest) SetTimeInterval(v *v1.TimeInterval) {
	x.xxx_hidden_TimeInterval = v
}

func (x *QueryLogsInIntervalRequest) SetPage(v *v1.Pagination) {
	x.xxx_hidden_Page = v
}

func (x *QueryLogsInIntervalRequest) SetSortDirection(v v1.SortDirection) {
	x.xxx_hidden_SortDirection = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *QueryLogsInIntervalRequest) HasTimeInterval() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TimeInterval != nil
}

func (x *QueryLogsInIntervalRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *QueryLogsInIntervalRequest) HasSortDirection() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *QueryLogsInIntervalRequest) ClearTimeInterval() {
	x.xxx_hidden_TimeInterval = nil
}

func (x *QueryLogsInIntervalRequest) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *QueryLogsInIntervalRequest) ClearSortDirection() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SortDirection = v1.SortDirection_SORT_DIRECTION_UNSPECIFIED
}

type QueryLogsInIntervalRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The start time of the interval to query logs for.
	TimeInterval *v1.TimeInterval
	// The pagination parameters for this request.
	Page *v1.Pagination
	// The direction in which to sort log entries. If not specified, defaults to descending order (newest entries first).
	SortDirection *v1.SortDirection
}

func (b0 QueryLogsInIntervalRequest_builder) Build() *QueryLogsInIntervalRequest {
	m0 := &QueryLogsInIntervalRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TimeInterval = b.TimeInterval
	x.xxx_hidden_Page = b.Page
	if b.SortDirection != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_SortDirection = *b.SortDirection
	}
	return m0
}

// PaginatedLogsData is the response message for paginated log queries. It's a message compatible with LogsData,
// but with an additional field for pagination parameters for the next page.
type PaginatedLogsData struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceLogs *[]*v11.ResourceLogs   `protobuf:"bytes,1,rep,name=resource_logs,json=resourceLogs"`
	xxx_hidden_NextPage     *v1.Pagination         `protobuf:"bytes,2,opt,name=next_page,json=nextPage"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PaginatedLogsData) Reset() {
	*x = PaginatedLogsData{}
	mi := &file_workflows_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedLogsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedLogsData) ProtoMessage() {}

func (x *PaginatedLogsData) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PaginatedLogsData) GetResourceLogs() []*v11.ResourceLogs {
	if x != nil {
		if x.xxx_hidden_ResourceLogs != nil {
			return *x.xxx_hidden_ResourceLogs
		}
	}
	return nil
}

func (x *PaginatedLogsData) GetNextPage() *v1.Pagination {
	if x != nil {
		return x.xxx_hidden_NextPage
	}
	return nil
}

func (x *PaginatedLogsData) SetResourceLogs(v []*v11.ResourceLogs) {
	x.xxx_hidden_ResourceLogs = &v
}

func (x *PaginatedLogsData) SetNextPage(v *v1.Pagination) {
	x.xxx_hidden_NextPage = v
}

func (x *PaginatedLogsData) HasNextPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NextPage != nil
}

func (x *PaginatedLogsData) ClearNextPage() {
	x.xxx_hidden_NextPage = nil
}

type PaginatedLogsData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// An array of ResourceLogs.
	ResourceLogs []*v11.ResourceLogs
	// The pagination parameters for the next page.
	NextPage *v1.Pagination
}

func (b0 PaginatedLogsData_builder) Build() *PaginatedLogsData {
	m0 := &PaginatedLogsData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResourceLogs = &b.ResourceLogs
	x.xxx_hidden_NextPage = b.NextPage
	return m0
}

// QueryJobLogsRequest is the request message for querying logs of a specific job, in ascending or descending order,
// with pagination support.
type QueryJobSpansRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_JobId         *v1.ID                 `protobuf:"bytes,1,opt,name=job_id,json=jobId"`
	xxx_hidden_Page          *v1.Pagination         `protobuf:"bytes,2,opt,name=page"`
	xxx_hidden_SortDirection v1.SortDirection       `protobuf:"varint,3,opt,name=sort_direction,json=sortDirection,enum=tilebox.v1.SortDirection"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *QueryJobSpansRequest) Reset() {
	*x = QueryJobSpansRequest{}
	mi := &file_workflows_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJobSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJobSpansRequest) ProtoMessage() {}

func (x *QueryJobSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryJobSpansRequest) GetJobId() *v1.ID {
	if x != nil {
		return x.xxx_hidden_JobId
	}
	return nil
}

func (x *QueryJobSpansRequest) GetPage() *v1.Pagination {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *QueryJobSpansRequest) GetSortDirection() v1.SortDirection {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_SortDirection
		}
	}
	return v1.SortDirection(0)
}

func (x *QueryJobSpansRequest) SetJobId(v *v1.ID) {
	x.xxx_hidden_JobId = v
}

func (x *QueryJobSpansRequest) SetPage(v *v1.Pagination) {
	x.xxx_hidden_Page = v
}

func (x *QueryJobSpansRequest) SetSortDirection(v v1.SortDirection) {
	x.xxx_hidden_SortDirection = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *QueryJobSpansRequest) HasJobId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_JobId != nil
}

func (x *QueryJobSpansRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *QueryJobSpansRequest) HasSortDirection() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *QueryJobSpansRequest) ClearJobId() {
	x.xxx_hidden_JobId = nil
}

func (x *QueryJobSpansRequest) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *QueryJobSpansRequest) ClearSortDirection() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SortDirection = v1.SortDirection_SORT_DIRECTION_UNSPECIFIED
}

type QueryJobSpansRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The ID of the job to query logs for.
	JobId *v1.ID
	// The pagination parameters for this request.
	Page *v1.Pagination
	// The direction in which to sort log entries. If not specified, defaults to ascending order (oldest entries first).
	SortDirection *v1.SortDirection
}

func (b0 QueryJobSpansRequest_builder) Build() *QueryJobSpansRequest {
	m0 := &QueryJobSpansRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_JobId = b.JobId
	x.xxx_hidden_Page = b.Page
	if b.SortDirection != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_SortDirection = *b.SortDirection
	}
	return m0
}

// PaginatedSpansData is the response message for paginated log queries. It's a message compatible with LogsData,
// but with an additional field for pagination parameters for the next page.
type PaginatedSpansData struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceSpans *[]*v12.ResourceSpans  `protobuf:"bytes,1,rep,name=resource_spans,json=resourceSpans"`
	xxx_hidden_NextPage      *v1.Pagination         `protobuf:"bytes,2,opt,name=next_page,json=nextPage"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PaginatedSpansData) Reset() {
	*x = PaginatedSpansData{}
	mi := &file_workflows_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedSpansData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedSpansData) ProtoMessage() {}

func (x *PaginatedSpansData) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PaginatedSpansData) GetResourceSpans() []*v12.ResourceSpans {
	if x != nil {
		if x.xxx_hidden_ResourceSpans != nil {
			return *x.xxx_hidden_ResourceSpans
		}
	}
	return nil
}

func (x *PaginatedSpansData) GetNextPage() *v1.Pagination {
	if x != nil {
		return x.xxx_hidden_NextPage
	}
	return nil
}

func (x *PaginatedSpansData) SetResourceSpans(v []*v12.ResourceSpans) {
	x.xxx_hidden_ResourceSpans = &v
}

func (x *PaginatedSpansData) SetNextPage(v *v1.Pagination) {
	x.xxx_hidden_NextPage = v
}

func (x *PaginatedSpansData) HasNextPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NextPage != nil
}

func (x *PaginatedSpansData) ClearNextPage() {
	x.xxx_hidden_NextPage = nil
}

type PaginatedSpansData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// An array of ResourceLogs.
	ResourceSpans []*v12.ResourceSpans
	// The pagination parameters for the next page.
	NextPage *v1.Pagination
}

func (b0 PaginatedSpansData_builder) Build() *PaginatedSpansData {
	m0 := &PaginatedSpansData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResourceSpans = &b.ResourceSpans
	x.xxx_hidden_NextPage = b.NextPage
	return m0
}

var File_workflows_v1_telemetry_proto protoreflect.FileDescriptor

const file_workflows_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1cworkflows/v1/telemetry.proto\x12\fworkflows.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&opentelemetry/proto/logs/v1/logs.proto\x1a(opentelemetry/proto/trace/v1/trace.proto\x1a\x13tilebox/v1/id.proto\x1a\x16tilebox/v1/query.proto\"\xb9\x01\n" +
	"\x13QueryJobLogsRequest\x12-\n" +
	"\x06job_id\x18\x01 \x01(\v2\x0e.tilebox.v1.IDB\x06\xbaH\x03\xc8\x01\x01R\x05jobId\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x16.tilebox.v1.PaginationB\x05\xaa\x01\x02\b\x01R\x04page\x12@\n" +
	"\x0esort_direction\x18\x03 \x01(\x0e2\x19.tilebox.v1.SortDirectionR\rsortDirection\"\xd0\x01\n" +
	"\x1aQueryLogsInIntervalRequest\x12=\n" +
	"\rtime_interval\x18\x01 \x01(\v2\x18.tilebox.v1.TimeIntervalR\ftimeInterval\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x16.tilebox.v1.PaginationB\x05\xaa\x01\x02\b\x01R\x04page\x12@\n" +
	"\x0esort_direction\x18\x03 \x01(\x0e2\x19.tilebox.v1.SortDirectionR\rsortDirection\"\x9f\x01\n" +
	"\x11PaginatedLogsData\x12N\n" +
	"\rresource_logs\x18\x01 \x03(\v2).opentelemetry.proto.logs.v1.ResourceLogsR\fresourceLogs\x12:\n" +
	"\tnext_page\x18\x02 \x01(\v2\x16.tilebox.v1.PaginationB\x05\xaa\x01\x02\b\x01R\bnextPage\"\xba\x01\n" +
	"\x14QueryJobSpansRequest\x12-\n" +
	"\x06job_id\x18\x01 \x01(\v2\x0e.tilebox.v1.IDB\x06\xbaH\x03\xc8\x01\x01R\x05jobId\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x16.tilebox.v1.PaginationB\x05\xaa\x01\x02\b\x01R\x04page\x12@\n" +
	"\x0esort_direction\x18\x03 \x01(\x0e2\x19.tilebox.v1.SortDirectionR\rsortDirection\"\xa4\x01\n" +
	"\x12PaginatedSpansData\x12R\n" +
	"\x0eresource_spans\x18\x01 \x03(\v2+.opentelemetry.proto.trace.v1.ResourceSpansR\rresourceSpans\x12:\n" +
	"\tnext_page\x18\x02 \x01(\v2\x16.tilebox.v1.PaginationB\x05\xaa\x01\x02\b\x01R\bnextPage2\xa4\x02\n" +
	"\x15TelemetryQueryService\x12R\n" +
	"\fQueryJobLogs\x12!.workflows.v1.QueryJobLogsRequest\x1a\x1f.workflows.v1.PaginatedLogsData\x12`\n" +
	"\x13QueryLogsInInterval\x12(.workflows.v1.QueryLogsInIntervalRequest\x1a\x1f.workflows.v1.PaginatedLogsData\x12U\n" +
	"\rQueryJobSpans\x12\".workflows.v1.QueryJobSpansRequest\x1a .workflows.v1.PaginatedSpansDataB\xb4\x01\n" +
	"\x10com.workflows.v1B\x0eTelemetryProtoP\x01Z?github.com/tilebox/tilebox-go/protogen/workflows/v1;workflowsv1\xa2\x02\x03WXX\xaa\x02\fWorkflows.V1\xca\x02\fWorkflows\\V1\xe2\x02\x18Workflows\\V1\\GPBMetadata\xea\x02\rWorkflows::V1b\beditionsp\xe8\a"

var file_workflows_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_workflows_v1_telemetry_proto_goTypes = []any{
	(*QueryJobLogsRequest)(nil),        // 0: workflows.v1.QueryJobLogsRequest
	(*QueryLogsInIntervalRequest)(nil), // 1: workflows.v1.QueryLogsInIntervalRequest
	(*PaginatedLogsData)(nil),          // 2: workflows.v1.PaginatedLogsData
	(*QueryJobSpansRequest)(nil),       // 3: workflows.v1.QueryJobSpansRequest
	(*PaginatedSpansData)(nil),         // 4: workflows.v1.PaginatedSpansData
	(*v1.ID)(nil),                      // 5: tilebox.v1.ID
	(*v1.Pagination)(nil),              // 6: tilebox.v1.Pagination
	(v1.SortDirection)(0),              // 7: tilebox.v1.SortDirection
	(*v1.TimeInterval)(nil),            // 8: tilebox.v1.TimeInterval
	(*v11.ResourceLogs)(nil),           // 9: opentelemetry.proto.logs.v1.ResourceLogs
	(*v12.ResourceSpans)(nil),          // 10: opentelemetry.proto.trace.v1.ResourceSpans
}
var file_workflows_v1_telemetry_proto_depIdxs = []int32{
	5,  // 0: workflows.v1.QueryJobLogsRequest.job_id:type_name -> tilebox.v1.ID
	6,  // 1: workflows.v1.QueryJobLogsRequest.page:type_name -> tilebox.v1.Pagination
	7,  // 2: workflows.v1.QueryJobLogsRequest.sort_direction:type_name -> tilebox.v1.SortDirection
	8,  // 3: workflows.v1.QueryLogsInIntervalRequest.time_interval:type_name -> tilebox.v1.TimeInterval
	6,  // 4: workflows.v1.QueryLogsInIntervalRequest.page:type_name -> tilebox.v1.Pagination
	7,  // 5: workflows.v1.QueryLogsInIntervalRequest.sort_direction:type_name -> tilebox.v1.SortDirection
	9,  // 6: workflows.v1.PaginatedLogsData.resource_logs:type_name -> opentelemetry.proto.logs.v1.ResourceLogs
	6,  // 7: workflows.v1.PaginatedLogsData.next_page:type_name -> tilebox.v1.Pagination
	5,  // 8: workflows.v1.QueryJobSpansRequest.job_id:type_name -> tilebox.v1.ID
	6,  // 9: workflows.v1.QueryJobSpansRequest.page:type_name -> tilebox.v1.Pagination
	7,  // 10: workflows.v1.QueryJobSpansRequest.sort_direction:type_name -> tilebox.v1.SortDirection
	10, // 11: workflows.v1.PaginatedSpansData.resource_spans:type_name -> opentelemetry.proto.trace.v1.ResourceSpans
	6,  // 12: workflows.v1.PaginatedSpansData.next_page:type_name -> tilebox.v1.Pagination
	0,  // 13: workflows.v1.TelemetryQueryService.QueryJobLogs:input_type -> workflows.v1.QueryJobLogsRequest
	1,  // 14: workflows.v1.TelemetryQueryService.QueryLogsInInterval:input_type -> workflows.v1.QueryLogsInIntervalRequest
	3,  // 15: workflows.v1.TelemetryQueryService.QueryJobSpans:input_type -> workflows.v1.QueryJobSpansRequest
	2,  // 16: workflows.v1.TelemetryQueryService.QueryJobLogs:output_type -> workflows.v1.PaginatedLogsData
	2,  // 17: workflows.v1.TelemetryQueryService.QueryLogsInInterval:output_type -> workflows.v1.PaginatedLogsData
	4,  // 18: workflows.v1.TelemetryQueryService.QueryJobSpans:output_type -> workflows.v1.PaginatedSpansData
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_workflows_v1_telemetry_proto_init() }
func file_workflows_v1_telemetry_proto_init() {
	if File_workflows_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflows_v1_telemetry_proto_rawDesc), len(file_workflows_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflows_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_workflows_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_workflows_v1_telemetry_proto_msgTypes,
	}.Build()
	File_workflows_v1_telemetry_proto = out.File
	file_workflows_v1_telemetry_proto_goTypes = nil
	file_workflows_v1_telemetry_proto_depIdxs = nil
}
