// The externally facing API allowing users to publish and deploy workflow task releases.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: workflows/v1/task_release.proto

package workflowsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/tilebox/tilebox-go/protogen/workflows/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskReleaseServiceName is the fully-qualified name of the TaskReleaseService service.
	TaskReleaseServiceName = "workflows.v1.TaskReleaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskReleaseServicePublishReleaseProcedure is the fully-qualified name of the TaskReleaseService's
	// PublishRelease RPC.
	TaskReleaseServicePublishReleaseProcedure = "/workflows.v1.TaskReleaseService/PublishRelease"
	// TaskReleaseServiceDeployReleaseProcedure is the fully-qualified name of the TaskReleaseService's
	// DeployRelease RPC.
	TaskReleaseServiceDeployReleaseProcedure = "/workflows.v1.TaskReleaseService/DeployRelease"
	// TaskReleaseServiceGetClusterDeploymentManifestProcedure is the fully-qualified name of the
	// TaskReleaseService's GetClusterDeploymentManifest RPC.
	TaskReleaseServiceGetClusterDeploymentManifestProcedure = "/workflows.v1.TaskReleaseService/GetClusterDeploymentManifest"
)

// TaskReleaseServiceClient is a client for the workflows.v1.TaskReleaseService service.
type TaskReleaseServiceClient interface {
	PublishRelease(context.Context, *connect.Request[v1.PublishReleaseRequest]) (*connect.Response[v1.PublishReleaseResponse], error)
	DeployRelease(context.Context, *connect.Request[v1.DeployReleaseRequest]) (*connect.Response[v1.DeployReleaseResponse], error)
	GetClusterDeploymentManifest(context.Context, *connect.Request[v1.GetClusterDeploymentManifestRequest]) (*connect.Response[v1.GetClusterDeploymentManifestResponse], error)
}

// NewTaskReleaseServiceClient constructs a client for the workflows.v1.TaskReleaseService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskReleaseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskReleaseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskReleaseServiceMethods := v1.File_workflows_v1_task_release_proto.Services().ByName("TaskReleaseService").Methods()
	return &taskReleaseServiceClient{
		publishRelease: connect.NewClient[v1.PublishReleaseRequest, v1.PublishReleaseResponse](
			httpClient,
			baseURL+TaskReleaseServicePublishReleaseProcedure,
			connect.WithSchema(taskReleaseServiceMethods.ByName("PublishRelease")),
			connect.WithClientOptions(opts...),
		),
		deployRelease: connect.NewClient[v1.DeployReleaseRequest, v1.DeployReleaseResponse](
			httpClient,
			baseURL+TaskReleaseServiceDeployReleaseProcedure,
			connect.WithSchema(taskReleaseServiceMethods.ByName("DeployRelease")),
			connect.WithClientOptions(opts...),
		),
		getClusterDeploymentManifest: connect.NewClient[v1.GetClusterDeploymentManifestRequest, v1.GetClusterDeploymentManifestResponse](
			httpClient,
			baseURL+TaskReleaseServiceGetClusterDeploymentManifestProcedure,
			connect.WithSchema(taskReleaseServiceMethods.ByName("GetClusterDeploymentManifest")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskReleaseServiceClient implements TaskReleaseServiceClient.
type taskReleaseServiceClient struct {
	publishRelease               *connect.Client[v1.PublishReleaseRequest, v1.PublishReleaseResponse]
	deployRelease                *connect.Client[v1.DeployReleaseRequest, v1.DeployReleaseResponse]
	getClusterDeploymentManifest *connect.Client[v1.GetClusterDeploymentManifestRequest, v1.GetClusterDeploymentManifestResponse]
}

// PublishRelease calls workflows.v1.TaskReleaseService.PublishRelease.
func (c *taskReleaseServiceClient) PublishRelease(ctx context.Context, req *connect.Request[v1.PublishReleaseRequest]) (*connect.Response[v1.PublishReleaseResponse], error) {
	return c.publishRelease.CallUnary(ctx, req)
}

// DeployRelease calls workflows.v1.TaskReleaseService.DeployRelease.
func (c *taskReleaseServiceClient) DeployRelease(ctx context.Context, req *connect.Request[v1.DeployReleaseRequest]) (*connect.Response[v1.DeployReleaseResponse], error) {
	return c.deployRelease.CallUnary(ctx, req)
}

// GetClusterDeploymentManifest calls workflows.v1.TaskReleaseService.GetClusterDeploymentManifest.
func (c *taskReleaseServiceClient) GetClusterDeploymentManifest(ctx context.Context, req *connect.Request[v1.GetClusterDeploymentManifestRequest]) (*connect.Response[v1.GetClusterDeploymentManifestResponse], error) {
	return c.getClusterDeploymentManifest.CallUnary(ctx, req)
}

// TaskReleaseServiceHandler is an implementation of the workflows.v1.TaskReleaseService service.
type TaskReleaseServiceHandler interface {
	PublishRelease(context.Context, *connect.Request[v1.PublishReleaseRequest]) (*connect.Response[v1.PublishReleaseResponse], error)
	DeployRelease(context.Context, *connect.Request[v1.DeployReleaseRequest]) (*connect.Response[v1.DeployReleaseResponse], error)
	GetClusterDeploymentManifest(context.Context, *connect.Request[v1.GetClusterDeploymentManifestRequest]) (*connect.Response[v1.GetClusterDeploymentManifestResponse], error)
}

// NewTaskReleaseServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskReleaseServiceHandler(svc TaskReleaseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskReleaseServiceMethods := v1.File_workflows_v1_task_release_proto.Services().ByName("TaskReleaseService").Methods()
	taskReleaseServicePublishReleaseHandler := connect.NewUnaryHandler(
		TaskReleaseServicePublishReleaseProcedure,
		svc.PublishRelease,
		connect.WithSchema(taskReleaseServiceMethods.ByName("PublishRelease")),
		connect.WithHandlerOptions(opts...),
	)
	taskReleaseServiceDeployReleaseHandler := connect.NewUnaryHandler(
		TaskReleaseServiceDeployReleaseProcedure,
		svc.DeployRelease,
		connect.WithSchema(taskReleaseServiceMethods.ByName("DeployRelease")),
		connect.WithHandlerOptions(opts...),
	)
	taskReleaseServiceGetClusterDeploymentManifestHandler := connect.NewUnaryHandler(
		TaskReleaseServiceGetClusterDeploymentManifestProcedure,
		svc.GetClusterDeploymentManifest,
		connect.WithSchema(taskReleaseServiceMethods.ByName("GetClusterDeploymentManifest")),
		connect.WithHandlerOptions(opts...),
	)
	return "/workflows.v1.TaskReleaseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskReleaseServicePublishReleaseProcedure:
			taskReleaseServicePublishReleaseHandler.ServeHTTP(w, r)
		case TaskReleaseServiceDeployReleaseProcedure:
			taskReleaseServiceDeployReleaseHandler.ServeHTTP(w, r)
		case TaskReleaseServiceGetClusterDeploymentManifestProcedure:
			taskReleaseServiceGetClusterDeploymentManifestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskReleaseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskReleaseServiceHandler struct{}

func (UnimplementedTaskReleaseServiceHandler) PublishRelease(context.Context, *connect.Request[v1.PublishReleaseRequest]) (*connect.Response[v1.PublishReleaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflows.v1.TaskReleaseService.PublishRelease is not implemented"))
}

func (UnimplementedTaskReleaseServiceHandler) DeployRelease(context.Context, *connect.Request[v1.DeployReleaseRequest]) (*connect.Response[v1.DeployReleaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflows.v1.TaskReleaseService.DeployRelease is not implemented"))
}

func (UnimplementedTaskReleaseServiceHandler) GetClusterDeploymentManifest(context.Context, *connect.Request[v1.GetClusterDeploymentManifestRequest]) (*connect.Response[v1.GetClusterDeploymentManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflows.v1.TaskReleaseService.GetClusterDeploymentManifest is not implemented"))
}
