// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: workflows/v1/telemetry.proto

package workflowsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/tilebox/tilebox-go/protogen/workflows/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelemetryQueryServiceName is the fully-qualified name of the TelemetryQueryService service.
	TelemetryQueryServiceName = "workflows.v1.TelemetryQueryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelemetryQueryServiceQueryJobLogsProcedure is the fully-qualified name of the
	// TelemetryQueryService's QueryJobLogs RPC.
	TelemetryQueryServiceQueryJobLogsProcedure = "/workflows.v1.TelemetryQueryService/QueryJobLogs"
	// TelemetryQueryServiceQueryLogsInIntervalProcedure is the fully-qualified name of the
	// TelemetryQueryService's QueryLogsInInterval RPC.
	TelemetryQueryServiceQueryLogsInIntervalProcedure = "/workflows.v1.TelemetryQueryService/QueryLogsInInterval"
	// TelemetryQueryServiceQueryJobSpansProcedure is the fully-qualified name of the
	// TelemetryQueryService's QueryJobSpans RPC.
	TelemetryQueryServiceQueryJobSpansProcedure = "/workflows.v1.TelemetryQueryService/QueryJobSpans"
)

// TelemetryQueryServiceClient is a client for the workflows.v1.TelemetryQueryService service.
type TelemetryQueryServiceClient interface {
	QueryJobLogs(context.Context, *connect.Request[v1.QueryJobLogsRequest]) (*connect.Response[v1.PaginatedLogsData], error)
	QueryLogsInInterval(context.Context, *connect.Request[v1.QueryLogsInIntervalRequest]) (*connect.Response[v1.PaginatedLogsData], error)
	QueryJobSpans(context.Context, *connect.Request[v1.QueryJobSpansRequest]) (*connect.Response[v1.PaginatedSpansData], error)
}

// NewTelemetryQueryServiceClient constructs a client for the workflows.v1.TelemetryQueryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelemetryQueryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelemetryQueryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telemetryQueryServiceMethods := v1.File_workflows_v1_telemetry_proto.Services().ByName("TelemetryQueryService").Methods()
	return &telemetryQueryServiceClient{
		queryJobLogs: connect.NewClient[v1.QueryJobLogsRequest, v1.PaginatedLogsData](
			httpClient,
			baseURL+TelemetryQueryServiceQueryJobLogsProcedure,
			connect.WithSchema(telemetryQueryServiceMethods.ByName("QueryJobLogs")),
			connect.WithClientOptions(opts...),
		),
		queryLogsInInterval: connect.NewClient[v1.QueryLogsInIntervalRequest, v1.PaginatedLogsData](
			httpClient,
			baseURL+TelemetryQueryServiceQueryLogsInIntervalProcedure,
			connect.WithSchema(telemetryQueryServiceMethods.ByName("QueryLogsInInterval")),
			connect.WithClientOptions(opts...),
		),
		queryJobSpans: connect.NewClient[v1.QueryJobSpansRequest, v1.PaginatedSpansData](
			httpClient,
			baseURL+TelemetryQueryServiceQueryJobSpansProcedure,
			connect.WithSchema(telemetryQueryServiceMethods.ByName("QueryJobSpans")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telemetryQueryServiceClient implements TelemetryQueryServiceClient.
type telemetryQueryServiceClient struct {
	queryJobLogs        *connect.Client[v1.QueryJobLogsRequest, v1.PaginatedLogsData]
	queryLogsInInterval *connect.Client[v1.QueryLogsInIntervalRequest, v1.PaginatedLogsData]
	queryJobSpans       *connect.Client[v1.QueryJobSpansRequest, v1.PaginatedSpansData]
}

// QueryJobLogs calls workflows.v1.TelemetryQueryService.QueryJobLogs.
func (c *telemetryQueryServiceClient) QueryJobLogs(ctx context.Context, req *connect.Request[v1.QueryJobLogsRequest]) (*connect.Response[v1.PaginatedLogsData], error) {
	return c.queryJobLogs.CallUnary(ctx, req)
}

// QueryLogsInInterval calls workflows.v1.TelemetryQueryService.QueryLogsInInterval.
func (c *telemetryQueryServiceClient) QueryLogsInInterval(ctx context.Context, req *connect.Request[v1.QueryLogsInIntervalRequest]) (*connect.Response[v1.PaginatedLogsData], error) {
	return c.queryLogsInInterval.CallUnary(ctx, req)
}

// QueryJobSpans calls workflows.v1.TelemetryQueryService.QueryJobSpans.
func (c *telemetryQueryServiceClient) QueryJobSpans(ctx context.Context, req *connect.Request[v1.QueryJobSpansRequest]) (*connect.Response[v1.PaginatedSpansData], error) {
	return c.queryJobSpans.CallUnary(ctx, req)
}

// TelemetryQueryServiceHandler is an implementation of the workflows.v1.TelemetryQueryService
// service.
type TelemetryQueryServiceHandler interface {
	QueryJobLogs(context.Context, *connect.Request[v1.QueryJobLogsRequest]) (*connect.Response[v1.PaginatedLogsData], error)
	QueryLogsInInterval(context.Context, *connect.Request[v1.QueryLogsInIntervalRequest]) (*connect.Response[v1.PaginatedLogsData], error)
	QueryJobSpans(context.Context, *connect.Request[v1.QueryJobSpansRequest]) (*connect.Response[v1.PaginatedSpansData], error)
}

// NewTelemetryQueryServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelemetryQueryServiceHandler(svc TelemetryQueryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telemetryQueryServiceMethods := v1.File_workflows_v1_telemetry_proto.Services().ByName("TelemetryQueryService").Methods()
	telemetryQueryServiceQueryJobLogsHandler := connect.NewUnaryHandler(
		TelemetryQueryServiceQueryJobLogsProcedure,
		svc.QueryJobLogs,
		connect.WithSchema(telemetryQueryServiceMethods.ByName("QueryJobLogs")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryQueryServiceQueryLogsInIntervalHandler := connect.NewUnaryHandler(
		TelemetryQueryServiceQueryLogsInIntervalProcedure,
		svc.QueryLogsInInterval,
		connect.WithSchema(telemetryQueryServiceMethods.ByName("QueryLogsInInterval")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryQueryServiceQueryJobSpansHandler := connect.NewUnaryHandler(
		TelemetryQueryServiceQueryJobSpansProcedure,
		svc.QueryJobSpans,
		connect.WithSchema(telemetryQueryServiceMethods.ByName("QueryJobSpans")),
		connect.WithHandlerOptions(opts...),
	)
	return "/workflows.v1.TelemetryQueryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelemetryQueryServiceQueryJobLogsProcedure:
			telemetryQueryServiceQueryJobLogsHandler.ServeHTTP(w, r)
		case TelemetryQueryServiceQueryLogsInIntervalProcedure:
			telemetryQueryServiceQueryLogsInIntervalHandler.ServeHTTP(w, r)
		case TelemetryQueryServiceQueryJobSpansProcedure:
			telemetryQueryServiceQueryJobSpansHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelemetryQueryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTelemetryQueryServiceHandler struct{}

func (UnimplementedTelemetryQueryServiceHandler) QueryJobLogs(context.Context, *connect.Request[v1.QueryJobLogsRequest]) (*connect.Response[v1.PaginatedLogsData], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflows.v1.TelemetryQueryService.QueryJobLogs is not implemented"))
}

func (UnimplementedTelemetryQueryServiceHandler) QueryLogsInInterval(context.Context, *connect.Request[v1.QueryLogsInIntervalRequest]) (*connect.Response[v1.PaginatedLogsData], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflows.v1.TelemetryQueryService.QueryLogsInInterval is not implemented"))
}

func (UnimplementedTelemetryQueryServiceHandler) QueryJobSpans(context.Context, *connect.Request[v1.QueryJobSpansRequest]) (*connect.Response[v1.PaginatedSpansData], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflows.v1.TelemetryQueryService.QueryJobSpans is not implemented"))
}
